"""db create

Revision ID: 33ff68fc90b6
Revises:
Create Date: 2023-07-21 02:34:55.204700

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "33ff68fc90b6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "submenus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("menu_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["menu_id"], ["menus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title", "menu_id", name="uq_submenu_title_menu_id"),
    )
    op.create_table(
        "dishes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("submenu_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["submenu_id"], ["submenus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title", "submenu_id", name="uq_dish_title_submenu_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dishes")
    op.drop_table("submenus")
    op.drop_table("menus")
    # ### end Alembic commands ###
